version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "GamerXtrem"
    assignees:
      - "GamerXtrem"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
    ignore:
      # Ignore major version updates for ML libraries (can be breaking)
      - dependency-name: "torch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "torchvision"
        update-types: ["version-update:semver-major"]
      - dependency-name: "numpy"
        update-types: ["version-update:semver-major"]
  
  # JavaScript/React Native dependencies
  - package-ecosystem: "npm"
    directory: "/ios-app"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "06:00"
    open-pull-requests-limit: 10
    reviewers:
      - "GamerXtrem"
    assignees:
      - "GamerXtrem"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "mobile"
    ignore:
      # Ignore React Native major updates (requires manual testing)
      - dependency-name: "react-native"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
  
  # Docker base images
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "GamerXtrem"
    assignees:
      - "GamerXtrem"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "GamerXtrem"
    assignees:
      - "GamerXtrem"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "ci/cd"
    allow:
      - dependency-type: "direct"
    ignore:
      # Pin major version updates for critical actions
      - dependency-name: "actions/checkout"
        update-types: ["version-update:semver-major"]
      - dependency-name: "actions/setup-python"
        update-types: ["version-update:semver-major"]

  # Composer dependencies for WordPress plugins (if needed)
  - package-ecosystem: "composer"
    directory: "/wp-plugin"
    schedule:
      interval: "monthly"
      day: "first-monday"
      time: "06:00"
    open-pull-requests-limit: 3
    reviewers:
      - "GamerXtrem"
    assignees:
      - "GamerXtrem"
    commit-message:
      prefix: "deps(wp)"
      include: "scope"
    labels:
      - "dependencies"
      - "wordpress"
      - "php"
    allow:
      - dependency-type: "direct"
