version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: nightscan_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alerting_rules.yml:/etc/prometheus/alerting_rules.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=30d'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api'
    restart: unless-stopped
    networks:
      - nightscan_monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: nightscan_grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=nightscan_admin_2025
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    restart: unless-stopped
    networks:
      - nightscan_monitoring

  alertmanager:
    image: prom/alertmanager:latest
    container_name: nightscan_alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
    restart: unless-stopped
    networks:
      - nightscan_monitoring

  node_exporter:
    image: prom/node-exporter:latest
    container_name: nightscan_node_exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    networks:
      - nightscan_monitoring

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: nightscan_postgres_exporter
    ports:
      - "9187:9187"
    environment:
      - DATA_SOURCE_NAME=postgresql://user:password@postgres:5432/nightscan?sslmode=disable
    restart: unless-stopped
    networks:
      - nightscan_monitoring
    depends_on:
      - postgres

  redis_exporter:
    image: oliver006/redis_exporter:latest
    container_name: nightscan_redis_exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis:6379
    restart: unless-stopped
    networks:
      - nightscan_monitoring
    depends_on:
      - redis

  # Application metrics endpoints
  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nightscan_nginx_exporter
    ports:
      - "9113:9113"
    command:
      - '-nginx.scrape-uri=http://nginx:8080/nginx_status'
    restart: unless-stopped
    networks:
      - nightscan_monitoring

volumes:
  prometheus_data:
  grafana_data:
  alertmanager_data:

networks:
  nightscan_monitoring:
    driver: bridge
    external: false