groups:
  - name: nightscan_vps_alerts
    rules:
      # System-level alerts
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High memory usage on VPS"
          description: "Memory usage is above 85% (current: {{ $value }}%)"

      - alert: HighDiskUsage
        expr: (1 - (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"})) * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High disk usage on VPS"
          description: "Disk usage is above 80% (current: {{ $value }}%)"

      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 10m
        labels:
          severity: warning
          service: system
        annotations:
          summary: "High CPU usage on VPS"
          description: "CPU usage is above 80% (current: {{ $value }}%)"

      # Container-level alerts
      - alert: ContainerDown
        expr: up{job=~"nightscan-.*"} == 0
        for: 2m
        labels:
          severity: critical
          service: docker
        annotations:
          summary: "NightScan container is down"
          description: "Container {{ $labels.job }} has been down for more than 2 minutes"

      - alert: ContainerHighMemory
        expr: (container_memory_usage_bytes{name=~"nightscan-.*"} / container_spec_memory_limit_bytes{name=~"nightscan-.*"}) * 100 > 90
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "Container memory usage high"
          description: "Container {{ $labels.name }} memory usage is above 90%"

      - alert: ContainerRestartingTooOften
        expr: rate(container_last_seen{name=~"nightscan-.*"}[5m]) > 0
        for: 5m
        labels:
          severity: warning
          service: docker
        annotations:
          summary: "Container restarting frequently"
          description: "Container {{ $labels.name }} is restarting too often"

      # Application-specific alerts
      - alert: WebApplicationDown
        expr: up{job="nightscan-web"} == 0
        for: 2m
        labels:
          severity: critical
          service: web
        annotations:
          summary: "NightScan web application is down"
          description: "Web application has been unreachable for more than 2 minutes"

      - alert: PredictionAPIDown
        expr: up{job="prediction-api"} == 0
        for: 2m
        labels:
          severity: critical
          service: api
        annotations:
          summary: "Prediction API is down"
          description: "Prediction API has been unreachable for more than 2 minutes"

      - alert: HighAPILatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{job="prediction-api"}[5m])) > 2
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "High API latency detected"
          description: "95th percentile latency is above 2 seconds (current: {{ $value }}s)"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) * 100 > 5
        for: 5m
        labels:
          severity: warning
          service: api
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 5% (current: {{ $value }}%)"

      # Database alerts
      - alert: PostgreSQLDown
        expr: up{job="postgres"} == 0
        for: 2m
        labels:
          severity: critical
          service: database
        annotations:
          summary: "PostgreSQL is down"
          description: "PostgreSQL database has been unreachable for more than 2 minutes"

      - alert: PostgreSQLTooManyConnections
        expr: pg_stat_activity_count / pg_settings_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
          service: database
        annotations:
          summary: "PostgreSQL connection usage high"
          description: "PostgreSQL connection usage is above 80%"

      # Redis alerts
      - alert: RedisDown
        expr: up{job="redis"} == 0
        for: 2m
        labels:
          severity: critical
          service: cache
        annotations:
          summary: "Redis is down"
          description: "Redis cache has been unreachable for more than 2 minutes"

      - alert: RedisMemoryUsageHigh
        expr: (redis_memory_used_bytes / redis_memory_max_bytes) * 100 > 90
        for: 5m
        labels:
          severity: warning
          service: cache
        annotations:
          summary: "Redis memory usage high"
          description: "Redis memory usage is above 90%"

      # SSL Certificate alerts
      - alert: SSLCertificateExpiringSoon
        expr: (ssl_certificate_expiry_seconds - time()) / 86400 < 30
        for: 1h
        labels:
          severity: warning
          service: ssl
        annotations:
          summary: "SSL certificate expiring soon"
          description: "SSL certificate will expire in less than 30 days"

      # Backup alerts
      - alert: BackupFailed
        expr: time() - backup_last_success_timestamp > 172800  # 48 hours
        for: 1h
        labels:
          severity: warning
          service: backup
        annotations:
          summary: "Backup has not run successfully"
          description: "No successful backup for more than 48 hours"