global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'nightscan-vps'
    environment: 'production'

rule_files:
  - "alerts.yml"

alerting:
  alertmanagers: []

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s

  # cAdvisor (container metrics)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s
    metrics_path: /metrics

  # NightScan Web Application
  - job_name: 'nightscan-web'
    static_configs:
      - targets: ['web:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # NightScan Prediction API
  - job_name: 'prediction-api'
    static_configs:
      - targets: ['prediction-api:8001']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # PostgreSQL Exporter (if available)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    params:
      sslmode: [disable]
    metrics_path: /metrics

  # Redis Exporter (if available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx metrics (if nginx-prometheus-exporter is available)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-proxy:9113']
    scrape_interval: 15s
    metrics_path: /metrics

storage:
  tsdb:
    retention.time: 7d
    retention.size: 2GB