name: 'Setup Python Environment'
description: 'Set up Python with caching and common dependencies'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.9'
  install-deps:
    description: 'Install dependencies from requirements.txt'
    required: false
    default: 'true'
  cache-key-prefix:
    description: 'Cache key prefix'
    required: false
    default: 'pip'

runs:
  using: 'composite'
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
    
    - name: Cache pip packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-${{ inputs.cache-key-prefix }}-${{ inputs.python-version }}-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.cache-key-prefix }}-${{ inputs.python-version }}-
          ${{ runner.os }}-${{ inputs.cache-key-prefix }}-
    
    - name: Upgrade pip
      shell: bash
      run: |
        python -m pip install --upgrade pip wheel setuptools
    
    - name: Install dependencies
      if: inputs.install-deps == 'true'
      shell: bash
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi
        if [ -f requirements-dev.txt ]; then
          pip install -r requirements-dev.txt
        fi
        if [ -f requirements-test.txt ]; then
          pip install -r requirements-test.txt
        fi